[package]
name = "nalu"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.1.0"
serde = {version = "1.0.130", features = ["derive"]}
byte_storage = { path = "../byte_storage" }
no_discrimination = { path = "../no_discrimination" }
vcd_parser = { path = "../vcd_parser" }
crossterm = "0.23.1"
tui = {version=  "0.17.0", path = "../tui-rs"}
